### ISSUE TITLE
[🚀] REST configure number of used Threads

### ISSUE THREAD

**Issue by finnWellers** [jeakfrw/jeak-framework#73] opened 2019-07-30 20:14 UTC
You can configure the thread pool of jetty. Per default we are using 1 Thread. Maybe we should increase this or make it at least configurable or both. When using multiple threads we have to make sure everything is threadsave (or show warnings if some controllers are not threadsave)

**Comment by MarkTwoFive** [comment] 2019-07-31 15:03
In my opinion, the convention should be that controllers have to be completely stateless, making them thread-safe by design.  
Asynchronous processing is everywhere in the framework as all listeners, tasks and callbacks are invoked asynchronously. Developers will learn to use and cope with that and good practice conventions can help with that.  
  
The thread pool should be around 4 or 5 by default, if you ask me. To me, one thread would not suffice as it will be exhausted with only one request already. 3 to 5 requests at the same time seems to be more reasonable to me for almost all non-high-load scenarios. (Especially since non-working threads should be put to sleep automatically anyways.)

**Comment by MarkTwoFive** [comment] 2019-07-31 15:04
Also, since other thread pool sizes are already configured this way, it will only be useful to have the thread pool size retrieved by ``Main#getProperty(String, int)`` with the default as the second argument.

**Comment by torge-hmn** [comment] 2019-08-06 19:04
As of today, I can say that this a highly demanded feature!

**Comment by MarkTwoFive** [comment] 2019-10-17 19:02
// closed by #110

**Closed as completed** 2019-10-17 19:02 UTC
Labels: enhancement, question, feedback wanted
